.\" Manpage for htrace.sh.
.\" Contact trimstray@gmail.com.
.TH man 8 "12.07.2018" "1.1.5" "htrace.sh man page"
.SH NAME
htrace.sh \- shell script for http/https troubleshooting and profiling.
.SH SYNOPSIS
htrace.sh <option|long-option>
.SH DESCRIPTION
htrace.sh is a shell script for http/https troubleshooting and profiling. It's also a simple wrapper around several open source security tools.
.SH OPTIONS
--help
        show this message

--version
        show script version

-u|--url <value>
        set target url with http/https protocol

-s|--ssl
        show basic ssl server/connection parameters

-h|--headers
        show response headers

-b|--body
        show response body

-M|--req-method <value>
        set request method (default: GET)

-H|--req-header <value>
        set request header(s)

-p|--proxy <value>
        set proxy server (not for external tools)

-r|--resolve <value>
        resolve the host+port to this address

-a|--all-scans
        use all external security tools

--testssl
        test ssl protocols and ciphers (testssl.sh)

--observatory
        analyze website headers (mozilla observatory)

--ssllabs
        deep analysis of the ssl web server (ssllabs)

--mixed-content
        scan website for non-secure resources (mixed-content-scan)

--nse
        scan website and domain with nse library (nmap)

--waf
        detect and bypass web application firewalls (whatwaf)

--dns
        enumerate subdomains (subfinder) and perform zone transfer

--cache-bypass <value>
        try (proxy) cache bypass

--user-agent <value>
        set 'User-Agent' header

--auth <value>
        set authentication method

--tlsv <value>
        set tls version

--max-redirects <num>
        set max redirects (default: 10)

--timeout <num>
        set max timeout (default: 15)

--hide-src-ip
        hide source ip from output
.SH SEE ALSO
https://github.com/trimstray/htrace.sh
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
