.\" Manpage for htrace.sh.
.\" Contact trimstray@gmail.com.
.TH man 8 "12.07.2018" "1.0.9" "htrace.sh man page"
.SH NAME
htrace.sh \- shell script for http/https troubleshooting and profiling.
.SH SYNOPSIS
htrace.sh <option|long-option>
.SH DESCRIPTION
htrace.sh is a simple shell script to debugging http/https connection tracing, response headers and mixed-content. Scanning domain using Nmap NSE Library. Support external security tools: testssl.sh, Mozilla Observatory and SSL Labs API.
.SH OPTIONS
--help
        show this message

-d|--domain <domain_name>
        set domain name

-s|--ssl
        show basic ssl server/connection parameters

-h|--headers
        show response headers

-b|--body
        show response body

-m|--method <value>
        set request method (default: GET)

-H|--header <value>
        set request header(s)

-p|--proxy
        set proxy server (not for external tools)

--testssl
        test ssl protocols and ciphers with testssl.sh

--observatory
        scan domain with mozilla observatory security tool

--ssllabs
        scan domain with ssllabs security tool

--mixed-content
        scan website for mixed content

--nse
        scan website with nmap nse library

--cache-bypass <value>
        try (proxy) cache bypass

--user-agent <value>
        set 'User-Agent' header

--max-redirects <num>
        set max redirects (default: 10)

--timeout <num>
        set max timeout (default: 15)

--hide-src-ip
        hide source ip from output
.SH SEE ALSO
https://github.com/trimstray/htrace.sh
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
