.\" Manpage for htrace.sh.
.\" Contact trimstray@gmail.com.
.TH man 8 "12.07.2018" "1.0.4" "htrace.sh man page"
.SH NAME
htrace.sh \- simple shell script to debugging http/https traffic tracing.
.SH SYNOPSIS
htrace.sh <option|long-option>
.SH DESCRIPTION
htrace.sh is a simple shell script to debugging http/https traffic tracing.
.SH OPTIONS
--help
        show this message

-d|--domain <domain_name>
        set domain name

-h|--headers
        show response headers

-s|--scan <all|observatory|ssllabs>
        scan domain with external security tools
.SH SEE ALSO
https://github.com/trimstray/htrace.sh
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
