.\" Manpage for htrace.sh.
.\" Contact trimstray@gmail.com.
.TH man 8 "12.07.2018" "1.0.4" "htrace.sh man page"
.SH NAME
htrace.sh \- simple shell script to debugging http/https traffic tracing, response headers and mixed-content.
.SH SYNOPSIS
htrace.sh <option|long-option>
.SH DESCRIPTION
htrace.sh is a simple shell script to debugging http/https traffic tracing, response headers and mixed-content. Support external security tools: Mozilla Observatory and SSL Labs API.
.SH OPTIONS
--help
        show this message

-d|--domain <domain_name>
        set domain name

-s|--ssl
        show ssl server/connection params

-h|--headers
        show response headers

--scan <all|observatory|ssllabs>
        scan domain with external security tools

--mixed-content
        scan website for mixed content

--max-redirects <num>
        set max redirects (default: 10)

--user-agent <val>
        set 'User-Agent' header
.SH SEE ALSO
https://github.com/trimstray/htrace.sh
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
