#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: CheckConn()
#
# Description:
#   Check connection to remote host.
#
# Usage:
#   CheckConn host port
#
# Examples:
#   CheckConn 172.20.20.50 22
#

function CheckConn() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="CheckConn"
  local _STATE=0

  local _host="$1"
  local _port="$2"

  # shellcheck disable=SC2154
  timeout 1 bash -c "</dev/tcp/${_host}/${_port}" >>"$_log_stdout" 2>&1

  if [[ "$?" -eq 1 ]] ; then

    # shellcheck disable=SC2034
    _STATE="1"

    _logger "stop" \
      "${_FUNCTION_ID}()" \
      "not properly connection to socket: ${_host}:${_port}"

  else

    # shellcheck disable=SC2034
    _STATE="0"

    _logger "info" \
      "${_FUNCTION_ID}()" \
      "properly connection to socket: ${_host}:${_port}"

  fi

  return $_STATE

}
