#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainScanObservatory()
#
# Description:
#   Scan domain with mozilla-observatory tool.
#
# Usage:
#   DomainScanObservatory domain
#
# Examples:
#   DomainScanObservatory example.com
#

function DomainScanObservatory() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainScanObservatory"
  local _STATE=0

  local _host="$1"

  # shellcheck disable=SC2034
  _destination_host="$_host"

  local _observatory_desc="Mozilla Observatory:https://observatory.mozilla.org"
  local _observatory_cmd="eval observatory \"$_host\" --format=report --rescan --zero --quiet"

  _msg_args+=(\
              "$_observatory_desc")

  _cmd_args+=(\
              "$_observatory_cmd")

  return $_STATE

}
