#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainScan()
#
# Description:
#   Scan domain with external tools.
#
# Usage:
#   DomainScan domain
#
# Examples:
#   DomainScan example.com
#

function DomainScan() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainScan"
  local _STATE=0

  local _scan_t="$1"
  local _host="$2"

  # shellcheck disable=SC2154
  if [[ "$_scan_t" = *"observatory"* ]] ; then

    local _observatory_desc="Mozilla Observatory:https://observatory.mozilla.org"
    local _observatory_cmd="eval observatory \"$_host\" --format=report --rescan --zero --quiet"

    _msg_args+=(\
                "$_observatory_desc")

    _cmd_args+=(\
                "$_observatory_cmd")

  elif [[ "$_scan_t" = *"ssllabs"* ]] ; then

    local _ssllabs_desc="Ssllabs API:https://www.ssllabs.com/ssltest/"
    local _ssllabs_cmd="eval ssllabs-scan -quiet -grade \"$_host\""

    _msg_args+=(\
                "$_ssllabs_desc")

    _cmd_args+=(\
                "$_ssllabs_cmd")

  fi

  return $_STATE

}
