#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainScanNmapNse()
#
# Description:
#   Scan domain with Nmap NSE Library.
#
# Usage:
#   DomainScanNmapNse domain port
#
# Examples:
#   DomainScanNmapNse example.com 443
#

function DomainScanNmapNse() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainScanNmapNse"
  local _STATE=0

  local _host="$1"
  local _port="$2"

  # shellcheck disable=SC2034
  _destination_host="$_host"

  local _nmap_nse_scripts="+dns-brute,\
                           +http-auth-finder,\
                           +http-chrono,\
                           +http-cookie-flags,\
                           +http-cors,\
                           +http-cross-domain-policy,\
                           +http-csrf,\
                           +http-dombased-xss,\
                           +http-enum,\
                           +http-errors,\
                           +http-git,\
                           +http-grep,\
                           +http-internal-ip-disclosure,\
                           +http-jsonp-detection,\
                           +http-malware-host,\
                           +http-methods,\
                           +http-passwd,\
                           +http-phpself-xss,\
                           +http-php-version,\
                           +http-robots.txt,\
                           +http-sitemap-generator,\
                           +http-shellshock,\
                           +http-stored-xss,\
                           +http-title,\
                           +http-unsafe-output-escaping,\
                           +http-useragent-tester,\
                           +http-vhosts,\
                           +http-waf-detect,\
                           +http-waf-fingerprint,\
                           +http-xssed,\
                           +traceroute-geolocation.nse,\
                           +ssl-enum-ciphers,\
                           +whois-domain,\
                           +whois-ip"

  local _nmap_nse_scripts_args="dns-brute.domain=${_host},"
        _nmap_nse_scripts_args+="http-cross-domain-policy.domain-lookup=true,"
        _nmap_nse_scripts_args+="http-waf-detect.aggro,"
        _nmap_nse_scripts_args+="http-waf-detect.detectBodyChanges,"
        _nmap_nse_scripts_args+="http-waf-fingerprint.intensive=1"

  local _mixed_content_desc="Scan domain with Nmap NSE Library:"
        _mixed_content_desc+="https://nmap.org/book/nse.html"

  # shellcheck disable=SC2034,SC2154
  local _mixed_content_cmd="eval nmap --script=\"$_nmap_nse_scripts\""
        _mixed_content_cmd+=" --script-args=\"$_nmap_nse_scripts_args\""
        _mixed_content_cmd+=" -p \"$_port\" \"$_host\""

  _msg_args+=(\
              "$_mixed_content_desc")

  _cmd_args+=(\
              "$_mixed_content_cmd")

  return $_STATE

}
