#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainSslCheck()
#
# Description:
#   Check ssl configuration.
#
# Usage:
#   DomainSslCheck domain
#
# Examples:
#   DomainSslCheck example.com
#

function DomainSslCheck() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainSslCheck"
  local _STATE=0

  # shellcheck disable=SC2034,SC2154
  _ssl_remote_socket="${_domain_ip}:${_domain_port}"
  # shellcheck disable=SC2154
  _ssl_domain_name="$_domain_name"

  # Default ssl params.
  _ssl_params_default=$(echo | \
                       openssl s_client -servername "$_ssl_domain_name" \
                       -connect "$_ssl_remote_socket" 2>/dev/null)

  _ssl_params_proto=$(echo "$_ssl_params_default" | \
                       grep "Protocol  :" | \
                       cut -d ":" -f2- | \
                       tr -d "[:space:]")

  _ssl_params_cipher=$(echo "$_ssl_params_default" | \
                       grep "Cipher    :" | \
                       cut -d ":" -f2- | \
                       tr -d "[:space:]")

  # This variable is used in InitTrace().
  # shellcheck disable=SC2034
  _ssl_params_verify=$(echo "$_ssl_params_default" | \
                       grep "Verification: \\|Verification error: " | \
                       cut -d ":" -f2- | \
                       awk '{$1=$1};1')

  if [[ "$_ssl_params_default" == *"no peer certificate available"* ]] ; then
     # [[ "$_ssl_params_default" == *"No client certificate CA names sent"* ]] ; then

    # shellcheck disable=SC2086,SC2154
    printf '\n    \e['${e_trgb}'m%s\e[m:\n\n\t%s\n\n' \
           "SSL error" \
           "- no peer certificate available"
           # "- no client certificate CA names sent"

    _logger "stop" \
      "${_FUNCTION_ID}()" \
      "no peer certificate available"
      # "no peer certificate available/no client certificate CA names sent"

  fi

  if [[ "$_ssl_params_proto" = *"TLSv1"* ]] ; then

    # shellcheck disable=SC2154
    local _ssl_trgb="0;0;32"

  else

    local _ssl_trgb="0;0;31"

  fi

  # shellcheck disable=SC2154
  if [[ "$ssl_state" -eq 1 ]] ; then

    printf '         ssl: \e['${g_trgb}'m%s\e[m, ' "on"

    # shellcheck disable=SC2086,SC2154
    printf 'version(\e['${_ssl_trgb}'m%s\e[m), cipher(\e['${v_trgb}'m%s\e[m)\n' \
           "$_ssl_params_proto" \
           "$_ssl_params_cipher"

  fi

  return $_STATE

}
