#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainStrip()
#
# Description:
#   Strip domain elements.
#
# Usage:
#   DomainStrip domain
#
# Examples:
#   DomainStrip example.com
#

function DomainStrip() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainStrip"
  local _STATE=0

  local _uri="$1"

  # Extract the protocol (includes trailing "://").
  _domain_proto=$(echo "$_uri" | sed -nr 's,^(.*://).*,\1,p')

  # shellcheck disable=SC2116
  # Remove the protocol from the URL.
  _domain_url_with_args=$(echo "${_uri/$_domain_proto/}")

  # shellcheck disable=SC2116
  # Remove all url args.
  _domain_url=$(echo "${_domain_url_with_args%/?}" | cut -d "?" -f1)

  # Extract the path (includes leading "/" or ":").
  _domain_path=$(echo "$_domain_url" | sed -nr 's,[^/:]*([/:].*),\1,p')

  # shellcheck disable=SC2116
  # Remove the path from the URL.
  _domain_name=$(echo "${_domain_url/$_domain_path/}")

  # shellcheck disable=SC2034
  # Resolve -d|--domain param value - if host.
  _domain_ip=$(DomainResolve "$_domain_name")

  # shellcheck disable=SC2034
  _domain_geoip=$(geoiplookup "$_domain_ip" | cut -d ":" -f2 | cut -d "," -f1 | tr -d " \\t\\n\\r")

  # printf "\\n%s: %s , %s: %s , %s: %s , %s: %s , %s: %s , %s: %s , %s: %s\\n\\n" \
  #        "_uri" "$_uri" \
  #        "_domain_proto" "$_domain_proto" \
  #        "_domain_url" "$_domain_url" \
  #        "_domain_path" "$_domain_path" \
  #        "_domain_name" "$_domain_name" \
  #        "_domain_ip" "$_domain_ip" \
  #        "_domain_geoip" "$_domain_geoip"

  return $_STATE

}
