#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainScan()
#
# Description:
#   Scan domain with external tools.
#
# Usage:
#   DomainScan domain
#
# Examples:
#   DomainScan example.com
#

function DomainScan() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainScan"
  local _STATE=0

  local _host="$1"

  local _observatory_desc="Mozilla Observatory:https://observatory.mozilla.org"
  local _observatory_cmd="eval observatory \"$_host\" --format=report --rescan --quiet"

  local _ssllabs_desc="ssllabs:https://www.ssllabs.com/ssltest/"
  local _ssllabs_cmd="eval ssllabs-scan -quiet -grade \"$_host\""

  # shellcheck disable=SC2154
  if [[ "$scan_type" = *"observatory"* ]] ; then

    _msg_args+=(\
                "$_observatory_desc")

    _cmd_args+=(\
                "$_observatory_cmd")

  elif [[ "$scan_type" = *"ssllabs"* ]] ; then

    _msg_args+=(\
                "$_ssllabs_desc")

    _cmd_args+=(\
                "$_ssllabs_cmd")

  elif [[ "$scan_type" == "all" ]] ; then

    _msg_args+=(\
                "$_observatory_desc" \
                "$_ssllabs_desc")

    _cmd_args+=(\
                "$_observatory_cmd" \
                "$_ssllabs_cmd")

  fi

  return $_STATE

}
