#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainScanMixedContent()
#
# Description:
#   Scan domain with for check mixed content.
#
# Usage:
#   DomainScanMixedContent domain
#
# Examples:
#   DomainScanMixedContent example.com
#

function DomainScanMixedContent() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainScanMixedContent"
  local _STATE=0

  local _host="$1"

  # shellcheck disable=SC2034
  _scan_type="active"

  # shellcheck disable=SC2034
  _destination_host="$_host"

  local _mixed_content_desc="Scan for non-secure resources:"
        _mixed_content_desc+="https://github.com/bramus/mixed-content-scan"

  # shellcheck disable=SC2154
  local _mixed_content_cmd="eval mixed-content-scan \"$_host\" --user-agent \"$_user_agent\""
        _mixed_content_cmd+=" --format no-ansi --no-check-certificate | grep \"MCS.[E|W]\""

  _msg_args+=(\
              "$_mixed_content_desc")

  _cmd_args+=(\
              "$_mixed_content_cmd")

  return $_STATE

}
