#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: DomainChainCheck()
#
# Description:
#   Check domain certificates chain.
#
# Usage:
#   DomainChainCheck domain
#
# Examples:
#   DomainChainCheck example.com
#

function DomainChainCheck() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="DomainChainCheck"
  local _STATE=0

  # shellcheck disable=SC2034,SC2154
  _ssl_remote_socket="${_domain_ip}:${_domain_port}"
  # shellcheck disable=SC2154
  _ssl_domain_name="$_domain_name"

  # shellcheck disable=SC2154
  if [[ -z "$_ssl_version_openssl_curl" ]] ; then

    _ssl_domain_cert_chain=$(echo | \
                       openssl s_client -verify 5 -servername "$_ssl_domain_name" \
                       -connect "$_ssl_remote_socket" 2>&1 | \
                       sed -ne '/Certificate chain/,/---/p')

  else

    _ssl_domain_cert_chain=$(echo | \
                       openssl s_client "$_ssl_version_openssl_curl" -verify 5 -servername "$_ssl_domain_name" \
                       -connect "$_ssl_remote_socket" 2>&1 | \
                       sed -ne '/Certificate chain/,/---/p')

  fi

  # shellcheck disable=SC2154
  if [[ "$_openssl_version" == "1.1.1a" ]] || \
     [[ "$_openssl_version" == "1.1.1b" ]] ; then

    _chain_verify_subjects=$(echo "$_ssl_domain_cert_chain" | \
                      grep -e "s:" | \
                      grep -o "CN =.*" | \
                      cut -d "=" -f2- | \
                      cut -d "," -f1 | \
                      awk '{$1=$1};1')

    _chain_verify_issuers=$(echo "$_ssl_domain_cert_chain" | \
                      grep -e "i:" | \
                      grep -o "CN =.*" | \
                      cut -d "=" -f2- | \
                      cut -d "," -f1 | \
                      awk '{$1=$1};1')

  else

    _chain_verify_subjects=$(echo "$_ssl_domain_cert_chain" | \
                      grep -e "s:/" | \
                      grep -o "/CN=.*" | \
                      cut -d "=" -f2- | \
                      cut -d "/" -f1 | \
                      awk '{$1=$1};1')

    _chain_verify_issuers=$(echo "$_ssl_domain_cert_chain" | \
                      grep -e "i:/" | \
                      grep -o "/CN=.*" | \
                      cut -d "=" -f2- | \
                      cut -d "/" -f1 | \
                      awk '{$1=$1};1')

  fi

  _chain_complete=()

  _chain_verify_subjects_stack=()
  _chain_verify_issuers_stack=()

  _chain_verify_subjects_stack_num=$(echo "$_chain_verify_subjects" | wc -l)
  _chain_verify_issuers_stack_num=$(echo "$_chain_verify_issuers" | wc -l)

  for i in $(seq 1 "$_chain_verify_subjects_stack_num") ; do

    _chain_verify_subjects_first=$(echo "$_chain_verify_subjects" | \
                    sed -n "${i}p" | cut -d "/" -f2- | cut -d "=" -f2-)

    _chain_verify_subjects_stack+=("${_chain_verify_subjects_first}")

  done

  for i in $(seq 1 "$_chain_verify_issuers_stack_num") ; do

    _chain_verify_issuers_first=$(echo "$_chain_verify_issuers" | \
                    sed -n "${i}p" | cut -d "/" -f2- | cut -d "=" -f2-)

    _chain_verify_issuers_stack+=("${_chain_verify_issuers_first}")

  done

  _first_certificate_status=0
  _last_certificate_status=0
  _last_certificate_duplicate=0
  _root_in_local_store=0

  _last_subject=$((_chain_verify_subjects_stack_num - 1))

  for i in $(seq 0 "$_last_subject") ; do

    # Verify the first certificate.
    if [[ "$i" -eq 0 ]] ; then

      # shellcheck disable=SC2154
      if [[ "${_chain_verify_subjects_stack[$i]}" == "$_ssl_domain_cn" ]] ; then

        _chain_complete+=("${_chain_verify_subjects_stack[$i]}")

        _first_certificate_status=1

      else

        _chain_complete+=("${_chain_verify_subjects_stack[$i]}")

      fi

    else

      if [[ "${_chain_verify_subjects_stack[$i]}" == "${_chain_verify_issuers_stack[$i]}" ]] ; then

        _last_certificate_duplicate=1

      elif [[ "$i" -eq "$_last_subject" ]] ; then

        _chain_complete+=("${_chain_verify_subjects_stack[$i]}")

      else

        _chain_complete+=("${_chain_verify_subjects_stack[$i]}")

      fi

    fi

  done

  _chain_complete+=("${_chain_verify_issuers_stack[$i]}")

  if [[ "$i" -eq "$_last_subject" ]] ; then

      # shellcheck disable=SC2034
      _last_certificate_status=1

      # shellcheck disable=SC2044,SC2154
      for j in $(find "$_ssl_ca_path" -name "*.pem") ; do

        # shellcheck disable=SC2116
        _root_certificate_cn=$(echo "${_chain_verify_issuers_stack[$i]}")

        # shellcheck disable=SC2154
        if openssl x509 -noout -subject -in "$j" | grep -q "$_root_certificate_cn" ; then

          _root_in_local_store=1

          _root_certificate_issuer=$(openssl x509 -noout -issuer -in "$j" | \
                     grep -o "CN =.*" | \
                     cut -d "=" -f2- | \
                     cut -d "/" -f1 | \
                     awk '{$1=$1};1')

          break

        else

          _root_in_local_store=0

        fi

      done

    fi

  _chain_of_trust_num="${#_chain_complete[@]}"

  # shellcheck disable=SC2086,SC2154
  printf '         chain of trust:'

  _last_subject_num=$((_chain_of_trust_num - 1))

  _t_rst=' '
  _x_rst='  '

  _c_counter="0"
  _init_certificate=0

  for k in $(seq 0 $((_chain_of_trust_num - 1))) ; do

    _c_counter=$((k + 1))

    if [[ "$_root_in_local_store" -eq 0 ]] ; then

      _root_certificate_issuer="$_chain_fa"

    fi

    if [[ "$_last_subject_num" -ne "$k" ]] || \
       [[ "$_root_in_local_store" -eq 1 ]] ; then

      # shellcheck disable=SC2086,SC2154
      printf '\n%s         └─\e['${trgb_3021}'m%s:%s\e[m' \
             "$_t_rst" "$k" "${_chain_complete[$k]}"

      _init_certificate=1

    elif [[ "$_root_certificate_issuer" == "${_chain_complete[$k]}" ]] ; then

      # shellcheck disable=SC2086
      printf '\n%s         └─\e['${trgb_3021}'m%s:%s\e[m' \
             "$_t_rst" "$k" "${_chain_complete[$k]}"

      _init_certificate=1

    else

      _init_certificate=0

    fi

    if [[ "$_init_certificate" -eq 1 ]] ; then

      if [[ "$_first_certificate_status" -eq 1 ]] && \
         [[ "$k" -eq 0 ]] ; then

        # shellcheck disable=SC2086,SC2154
        printf ' \e['${trgb_3300}'m%s\e[m' \
               "★"

      fi

      if [[ "${_chain_verify_subjects_stack[$k]}" == "$_ssl_domain_cn" ]] ; then

        # shellcheck disable=SC2154
        if [[ "$_validity_state" -eq 0 ]] ; then

          # shellcheck disable=SC2086,SC2154
          printf ' \e['${trgb_3200}'m%s\e[m' \
                 "✓"

        else

          # shellcheck disable=SC2086
          printf ' \e['${trgb_3100}'m%s\e[m' \
                 "!"

        fi

      elif [[ "$_chain_fa" == "$_chain_fb" ]] ; then

        # shellcheck disable=SC2086
        printf ' \e['${trgb_3200}'m%s\e[m' \
               "✓"

      elif [[ "$_root_certificate_issuer" == "$_chain_fb" ]] ; then

        # shellcheck disable=SC2086
        printf ' \e['${trgb_3200}'m%s\e[m' \
               "✓"

      else

        # shellcheck disable=SC2086
        printf ' \e['${trgb_3100}'m%s\e[m' \
               "×"

      fi

      if [[ "$_root_in_local_store" -eq 1 ]] && \
         [[ "$_last_subject_num" -eq "$k" ]] ; then

        # shellcheck disable=SC2086
        printf ' \e['${trgb_3300}'m%s\e[m' \
               "⊙"

      elif [[ "$_root_in_local_store" -eq 0 ]] && \
           [[ "$_last_subject_num" -eq "$k" ]] ; then

        # shellcheck disable=SC2086
        printf ' \e['${trgb_3100}'m%s\e[m' \
               "⊙"

      fi

      if [[ "$_last_certificate_duplicate" -eq 1 ]] && \
         [[ "$_last_subject_num" -eq "$k" ]] ; then

        # shellcheck disable=SC2086
        printf ' \e['${trgb_3300}'m%s\e[m' \
                 "2x"

      fi

    fi

    if [[ "${_chain_verify_subjects_stack[$k]}" != "${_chain_verify_issuers_stack[$k]}" ]] ; then

      if [[ "$_root_in_local_store" -eq 1 ]] ; then

        # shellcheck disable=SC2086,SC2154
        printf '\n%s           ├   \e['${trgb_3812}'m%s\e[m' \
               "$_t_rst" "${_chain_verify_issuers_stack[$k]}"

      elif [[ "$_root_in_local_store" -eq 0 ]] ; then

        # shellcheck disable=SC2086
        printf '\n%s           ├   \e['${trgb_3812}'m%s\e[m' \
               "$_t_rst" "${_chain_verify_issuers_stack[$k]}"

      fi

    elif [[ "$_root_certificate_issuer" == "${_chain_complete[$k]}" ]] ; then

      # shellcheck disable=SC2086
      printf '\n%s           └ \e['${trgb_3812}'m%s\e[m' \
             "$_t_rst" "${_chain_complete[$k]}"

    elif [[ "$_root_in_local_store" -eq 1 ]] ; then

      # shellcheck disable=SC2086
      printf '\n%s           └ \e['${trgb_3812}'m%s\e[m' \
             "$_t_rst" "${_chain_complete[$k]}"

    fi

    _chain_fa="${_chain_complete[$_c_counter]}"
    _chain_fb="${_chain_verify_issuers_stack[$k]}"

    _t_rst+="$_x_rst"

  done

  echo

  return $_STATE

}
