#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: SslCheck()
#
# Description:
#   Check ssl configuration.
#
# Usage:
#   SslCheck domain
#
# Examples:
#   SslCheck example.com
#

function SslCheck() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="SslCheck"
  local _STATE=0

  # shellcheck disable=SC2034,SC2154
  _ssl_domain_name="$_domain_name"

  _ssl_params=$(echo | \
                openssl s_client -servername "$_ssl_domain_name" -connect "$_ssl_domain_name":443 2>/dev/null | \
                grep "Protocol  :\\|Cipher    :\\|subject=")

  _ssl_params_proto=$(echo "$_ssl_params" | grep "Protocol  :" | cut -d ":" -f2- | tr -d "[:space:]")
  _ssl_params_cipher=$(echo "$_ssl_params" | grep "Cipher    :" | cut -d ":" -f2- | tr -d "[:space:]")
  # _ssl_params_cn=$(echo "$_ssl_params" | grep -o "/CN=.*" | cut -d "=" -f2- | tr -d "[:space:]")

  local _d_trgb="2;2;34"

  if [[ "$_ssl_params_proto" = *"TLSv1"* ]] ; then

    local _ssl_trgb="0;0;32"

  else

    local _ssl_trgb="0;0;31"

  fi

  printf '         ssl: \e[1;1;32m%s\e[m, ' "on"
  printf 'tls(\e['${_ssl_trgb}'m%s\e[m), cipher(\e['${_d_trgb}'m%s\e[m)\n' \
         "$_ssl_params_proto" \
         "$_ssl_params_cipher"

    return $_STATE

}
